"""KMTech source-only CNG cryptography contract."""

from .cng_p256 import (
    CngError,
    JwsErrorCodes,
    P256ContractError,
    P256JwsError,
    P256KeyError,
    P256KeyPair,
    P256SignatureError,
    b64url_decode,
    b64url_encode,
    canonical_json_bytes,
    generate_public_jwk,
    jwk_thumbprint,
    normalize_public_jwk,
    sign_compact_jws,
    verify_compact_jws,
    verify_es256,
)
from .possession_key import (
    ADMIN_RECOVERY_ACTION,
    AdminRecoveryRequired,
    DEFAULT_KEY_NAME,
    DEFAULT_KEY_SCOPE,
    ExportPolicyViolation,
    KeyDescriptor,
    KeyPolicyError,
    MS_KEY_STORAGE_PROVIDER,
    MS_PLATFORM_CRYPTO_PROVIDER,
    NCryptError,
    NonExportabilityProof,
    POSSESSION_KEY_CONTRACT_VERSION,
    PersistentPossessionKey,
    REATTACH_AUDIENCE,
    REATTACH_CANONICAL_KEY_ORDER,
    REATTACH_PROOF_CONTRACT_VERSION,
    REATTACH_PROOF_FIELDS,
    ReattachProofError,
    SCOPE_CURRENT_USER,
    SCOPE_LOCAL_MACHINE,
    validated_reattach_proof,
)
from .gdi_print import (
    GdiPrinter,
    MarginsMM,
    PaperSpec,
    PrinterError,
    PrintReceipt,
    PrintSpec,
)
from .raster import FontSpec, GdiRenderError, RasterCanvas, RasterError, RasterImage


CONTRACT_VERSION = "kmtech-zero-pe-contract-v1+possession-ncrypt-v1"


__all__ = [
    "ADMIN_RECOVERY_ACTION",
    "AdminRecoveryRequired",
    "CONTRACT_VERSION",
    "CngError",
    "DEFAULT_KEY_NAME",
    "DEFAULT_KEY_SCOPE",
    "ExportPolicyViolation",
    "FontSpec",
    "GdiPrinter",
    "GdiRenderError",
    "JwsErrorCodes",
    "KeyDescriptor",
    "KeyPolicyError",
    "MS_KEY_STORAGE_PROVIDER",
    "MS_PLATFORM_CRYPTO_PROVIDER",
    "NCryptError",
    "NonExportabilityProof",
    "P256ContractError",
    "P256JwsError",
    "P256KeyError",
    "P256KeyPair",
    "P256SignatureError",
    "PaperSpec",
    "POSSESSION_KEY_CONTRACT_VERSION",
    "PersistentPossessionKey",
    "PrinterError",
    "PrintReceipt",
    "PrintSpec",
    "REATTACH_AUDIENCE",
    "REATTACH_CANONICAL_KEY_ORDER",
    "REATTACH_PROOF_CONTRACT_VERSION",
    "REATTACH_PROOF_FIELDS",
    "ReattachProofError",
    "SCOPE_CURRENT_USER",
    "SCOPE_LOCAL_MACHINE",
    "RasterCanvas",
    "RasterError",
    "RasterImage",
    "b64url_decode",
    "b64url_encode",
    "canonical_json_bytes",
    "generate_public_jwk",
    "jwk_thumbprint",
    "normalize_public_jwk",
    "sign_compact_jws",
    "validated_reattach_proof",
    "verify_compact_jws",
    "verify_es256",
]
