name: Create GitHub Release for Label_Match

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller (One-Folder mode)
        # 아이콘 지정 및 hidden-import 옵션을 포함한 최종 명령어
        run: pyinstaller --name "Label_Match" --onedir --windowed --icon="assets/logo.ico" --add-data "assets;assets" --add-data "config;config" --hidden-import pygame --hidden-import Pillow Label_Match.py

      - name: Zip the build folder
        # 빌드된 폴더 전체(dist/Label_Match)를 압축합니다.
        run: |
          Compress-Archive -Path dist/Label_Match -DestinationPath "Label_Match-${{ github.ref_name }}.zip"
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "Label_Match-${{ github.ref_name }}.zip"
          name: "Release ${{ github.ref_name }}"
          body: "New release version ${{ github.ref_name }}"
          draft: false
          prerelease: false